### ISSUE TITLE
Tool is connecting to my mouse instead of the ESP8266

### ISSUE THREAD

**Issue by codingneko** [realmrvodka/n2d#1]
Hey, I'm just trying out this tool and I have my mouse connected on COM1, and it happens to be detected as a serial connection, when I try flashing the firmware on the ESP8266 it auto-selects COM1 but my ESP is on COM8...

Here is n2d's output:
![image](https://user-images.githubusercontent.com/11065075/58419408-d3df9c00-808a-11e9-9272-1ef030d9e2c1.png)

Here is the Arduino IDE configuration I am using (ESP on COM8 as you can see):
![image](https://user-images.githubusercontent.com/11065075/58419526-2751ea00-808b-11e9-92aa-291b7518e40f.png)

**Comment by ghost** [comment]
**Hi codingneko,** 

Thank you for raising this issue. This is because N2D looks for the first available COM Port and assumes it is the right one. Unfortunately at the moment you will have to unplug your mouse while attempting to flash your device with N2D. I am working on an algorithm for detecting the right device and I hope to get it out within a week or two. I am also going to add a COM Port selection so you can manually choose your COM Port.

**mrvoda007**

**Comment by ghost** [comment]
Hello again, I have updated the program and it should be working fine now. If not, feel free to open another issue. Thanks :smile:

**Comment by codingneko** [comment]
Awesome! that was fast :open_mouth: I'll have a look when I get home, thank you so much!

**Comment by ghost** [comment]
It sure was, I realized how simple of a fix it was. :)
