### ISSUE TITLE
DSTIKE deauther wristband

### ISSUE THREAD

**Issue by Acronix666** [realmrvodka/n2d#25]
Hello! I recently received my DSTIKE deauther wristband and i saw that on the official website the guy released 2.6 version of the firmware. I tried to flash it but now nothing shows on the screen of the wristband. Could it be that i flashed the wrong firmware? If so did i fry anything? Also what version is the right one for my device. I need help im new to all of this and im short of ideas. Thanks much ! :D

**Comment by ghost** [comment]
Hey, it is very possible that you might've flashed the wrong firmware since there are many DSTIKE versions. Don't worry! As far as I'm aware you cannot fry anything by flashing wrong firmware. You'll need to identify your DSTIKE version and select it from the program menu. I can't help with identifying because I don't personally own any myself (NodeMCU only) so you'll need to ask on the main repo.

Good luck!
