### ISSUE TITLE
I want to tweak around with the source code

### ISSUE THREAD

**Issue by chiragvshroff** [realmrvodka/n2d#4]
Hey i wanna change some stuff in the source code may i know how? cause im only pro at java lol.

**Comment by ghost** [comment]
To get started you'll need to download [Visual Studio 2019](https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=Community&rel=16 "Microsoft") and then learn C#. It's quite similar to Java in terms of syntax but you'll need to get used to its libraries. Since you're coming from Java that normally runs under a JVM you'll be happy with this since it's a bit faster (JIT) but I'd prefer Delphi because it compiles to native code and is much easier than C++ and Win32 Programming as you get a designer but I'm not a fan of Pascal.
